imports:
    - config/fields-container.yml

services:
    field:
        class:     'Opine\Field\Service'
        arguments: ['%root%', '@db']
    fieldModel:
        class:     'Opine\Field\Model'
        arguments: ['%root%']