services:
    fieldCheckBoxMulti:
        class:     Field\CheckBoxMulti
        arguments: [@field]
    fieldCheckboxesList:
        class:     Field\InputCheckboxesList
        arguments: [@field]
    fieldCheckboxes:
        class:     Field\InputCheckboxes
        arguments: [@field]
    fieldCheckboxNaked:
        class:     Field\InputCheckboxNaked
        arguments: [@field]
    fieldCheckbox:
        class:     Field\InputCheckbox
        arguments: [@field]
    fieldCodename:
        class:     Field\InputCodename
        arguments: [@field]
    fieldDatePicker:
        class:     Field\InputDatePicker
        arguments: [@field]
    fieldFileMulti:
        class:     Field\InputFileMulti
        arguments: [@field]
    fieldFile:
        class:     Field\InputFile
        arguments: [@field]
    fieldHidden:
        class:     Field\InputHidden
        arguments: [@field]
    fieldPassword:
        class:     Field\InputPassword
        arguments: [@field]
    fieldRadioList:
        class:     Field\InputRadioList
        arguments: [@field]
    fieldRadio:
        class:     Field\InputRadio
        arguments: [@field]
    fieldSlider:
        class:     Field\InputSlider
        arguments: [@field]
    fieldText:
        class:     Field\InputText
        arguments: [@field]
    fieldTags:
        class:     Field\InputToTags
        arguments: [@field]
    fieldManager:
        class:     Field\Manager
        arguments: [@field, @managerController]
    fieldRedactor:
        class:     Field\Redactor
        arguments: [@field]
    fieldSelect:
        class:     Field\Select
        arguments: [@field]
    fieldTextarea:
        class:     Field\Textarea
        arguments: [@field]