imports:
    - fields-container.yml

services:
    field:
        class:     Opine\Field\Service
        arguments: [%root%, @db, @route]
    fieldModel:
        class:     Opine\Field\Model
        arguments: [%root%]
